// Mock data for development/testing without TMDB API
import { SearchResponse, TrendingResponse } from '@/types/api';
import { Movie } from '@/types/movie';
import { Season, TVSeries, TVSeriesDetails } from '@/types/tv';

export const mockMovies: Movie[] = [
  {
    id: 1,
    title: "Don't Worry Darling",
    poster_path: '/1BxJLLXJW6D4bnarI99wCfw6Iod.jpg',
    backdrop_path: '/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg',
    overview: 'A 1950s housewife living with her husband in a utopian experimental community begins to worry that his glamorous company could be hiding disturbing secrets.',
    release_date: '2022-09-21',
    vote_average: 6.8,
    vote_count: 1523,
    adult: false,
    genre_ids: [53, 18],
    original_language: 'en',
    original_title: "Don't Worry Darling",
    popularity: 254.321,
    video: false,
  },
  {
    id: 2,
    title: 'Double Mommy',
    poster_path: '/nGwYdM6vBW0cMg8aFQdXo63c4GU.jpg',
    backdrop_path: '/aT14IZhPptkKhGvmAgOEJ6v9A5r.jpg',
    overview: 'When a troubled teen becomes pregnant, she must decide whether to keep the baby or give it up for adoption.',
    release_date: '2016-04-23',
    vote_average: 6.2,
    vote_count: 45,
    adult: false,
    genre_ids: [53, 18],
    original_language: 'en',
    original_title: 'Double Mommy',
    popularity: 12.456,
    video: false,
  },
  {
    id: 3,
    title: 'Crazy Kind of Love',
    poster_path: '/oPZvdS6jXQf3BmSJYtdgWPm4hT0.jpg',
    backdrop_path: '/1LHCk3W1OKZ4y3sSXJvKS5M7K8s.jpg',
    overview: 'A broken family finds their lives turned upside down when a young, street-smart grifter shows up on their doorstep.',
    release_date: '2013-06-14',
    vote_average: 5.8,
    vote_count: 89,
    adult: false,
    genre_ids: [35, 10749],
    original_language: 'en',
    original_title: 'Crazy Kind of Love',
    popularity: 8.234,
    video: false,
  },
  {
    id: 4,
    title: 'Christmas in the Highlands',
    poster_path: '/3VbXm4vy4HvFpgNzCLYlAKaVSaC.jpg',
    backdrop_path: '/k4vgWN7HHPBSaFWDn9H0cqPfPRx.jpg',
    overview: 'A New York ad exec travels to a small Scottish village to buy a castle, but the owner is reluctant to sell.',
    release_date: '2019-12-07',
    vote_average: 7.1,
    vote_count: 234,
    adult: false,
    genre_ids: [10749, 10770],
    original_language: 'en',
    original_title: 'Christmas in the Highlands',
    popularity: 45.678,
    video: false,
  },
  {
    id: 5,
    title: 'Changeling',
    poster_path: '/hZwhHnajdZvwE89hRgc4T7wVJHK.jpg',
    backdrop_path: '/38PkhBGjL4AXI6mDJp9BfmCwI6m.jpg',
    overview: "A mother's prayer for her kidnapped son to return home is answered, though it doesn't take long for her to suspect the boy who comes back is not hers.",
    release_date: '2008-10-24',
    vote_average: 7.6,
    vote_count: 3456,
    adult: false,
    genre_ids: [80, 18, 9648],
    original_language: 'en',
    original_title: 'Changeling',
    popularity: 89.123,
    video: false,
  },
  {
    id: 6,
    title: 'Blood Shot',
    poster_path: '/2wgieJLjKhSzXRmVOQiB5nMqDp9.jpg',
    backdrop_path: '/g8rj3k5xVK9z1vkJ8qRJW8Z5q5D.jpg',
    overview: 'A cop who takes the law into his own hands when his wife is kidnapped.',
    release_date: '2013-08-01',
    vote_average: 4.5,
    vote_count: 67,
    adult: false,
    genre_ids: [28, 53],
    original_language: 'en',
    original_title: 'Blood Shot',
    popularity: 15.234,
    video: false,
  },
];

export const mockTVSeries: TVSeries[] = [
  {
    id: 1,
    name: 'The Bachelor',
    poster_path: '/qbj7F0OqUb6K6lZKfIvCNcvBT3V.jpg',
    backdrop_path: '/1yNRnZbgfX4JMuR4BxFVKd5K5NV.jpg',
    overview: 'A single bachelor dates multiple women over several weeks, narrowing them down to hopefully find his true love.',
    first_air_date: '2002-03-25',
    vote_average: 5.5,
    vote_count: 234,
    popularity: 87.234,
    genre_ids: [10764],
    original_language: 'en',
    original_name: 'The Bachelor',
    origin_country: ['US'],
  },
  {
    id: 2,
    name: "RuPaul's Drag Race",
    poster_path: '/6LThfVcGWSLswQaQh2Z9XFbj1qX.jpg',
    backdrop_path: '/mKBP1LKiJKLGxu5VYLU8TJHU6qK.jpg',
    overview: 'Join RuPaul, the most famous drag queen in the world, as the host, mentor and inspiration on RuPaul\'s Drag Race.',
    first_air_date: '2009-02-02',
    vote_average: 7.5,
    vote_count: 456,
    popularity: 124.567,
    genre_ids: [10764],
    original_language: 'en',
    original_name: "RuPaul's Drag Race",
    origin_country: ['US'],
  },
  {
    id: 3,
    name: 'Gastronauts',
    poster_path: '/aJ3N0GI1OMNkQ1iZLcQRdCG3L9j.jpg',
    backdrop_path: '/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg',
    overview: 'Culinary adventures around the world exploring different cuisines and cultures.',
    first_air_date: '2020-01-15',
    vote_average: 8.2,
    vote_count: 178,
    popularity: 45.123,
    genre_ids: [99],
    original_language: 'en',
    original_name: 'Gastronauts',
    origin_country: ['US'],
  },
  {
    id: 4,
    name: 'Mountain Men',
    poster_path: '/lBbvZVPW7sxu9fGbSxBlMBVqpCN.jpg',
    backdrop_path: '/sjRPqD6jz4nBFvPMJi8rQj6pNZm.jpg',
    overview: 'Profiles of people who have chosen to live off the grid in the wilderness.',
    first_air_date: '2012-05-31',
    vote_average: 7.8,
    vote_count: 289,
    popularity: 67.890,
    genre_ids: [99],
    original_language: 'en',
    original_name: 'Mountain Men',
    origin_country: ['US'],
  },
  {
    id: 5,
    name: 'Adventure Time',
    poster_path: '/qk3eQ8jW4opJ48gFWYUXWaMT4l.jpg',
    backdrop_path: '/d2AHyM9R3L7rCR6Gc5xD2d0AX7u.jpg',
    overview: 'A 12-year-old boy and his best friend, a wise 28-year-old dog with magical powers, go on a series of surreal adventures in a remote future.',
    first_air_date: '2010-04-05',
    vote_average: 8.5,
    vote_count: 2345,
    popularity: 234.567,
    genre_ids: [16, 35, 10759],
    original_language: 'en',
    original_name: 'Adventure Time',
    origin_country: ['US'],
  },
  {
    id: 6,
    name: 'Law & Order',
    poster_path: '/m9TXYgjn58BZiqH4HBxlnvP9wWD.jpg',
    backdrop_path: '/pEKWH9HfV4Q1C0J8aWfVJvp7Sfa.jpg',
    overview: 'In cases ripped from the headlines, police investigate serious and often deadly crimes, weighing the evidence and questioning the suspects.',
    first_air_date: '1990-09-13',
    vote_average: 7.4,
    vote_count: 567,
    popularity: 156.789,
    genre_ids: [80, 18],
    original_language: 'en',
    original_name: 'Law & Order',
    origin_country: ['US'],
  },
];

// Mock API response formatters
export const createMockMovieResponse = (movies: Movie[]): SearchResponse<Movie> => ({
  page: 1,
  results: movies,
  total_pages: 1,
  total_results: movies.length,
});

export const createMockTVResponse = (series: TVSeries[]): SearchResponse<TVSeries> => ({
  page: 1,
  results: series,
  total_pages: 1,
  total_results: series.length,
});

export const createMockTrendingResponse = <T>(items: T[]): TrendingResponse<T> => ({
  page: 1,
  results: items,
  total_pages: 1,
  total_results: items.length,
});

// Mock TV Series Details
export const createMockTVDetails = (series: TVSeries): TVSeriesDetails => ({
  ...series,
  genres: [
    { id: 18, name: 'Drama' },
    { id: 10765, name: 'Sci-Fi & Fantasy' },
  ],
  episode_run_time: [45, 60],
  number_of_episodes: 20,
  number_of_seasons: 2,
  seasons: [
    {
      id: 1,
      name: 'Season 1',
      episode_count: 10,
      season_number: 1,
      air_date: '2021-11-06',
      overview: 'The first season introduces the characters and their world.',
      poster_path: series.poster_path,
    },
    {
      id: 2,
      name: 'Season 2',
      episode_count: 10,
      season_number: 2,
      air_date: '2024-11-09',
      overview: 'The story continues with new challenges.',
      poster_path: series.poster_path,
    },
  ],
  status: 'Returning Series',
  tagline: 'Every legend has a beginning.',
  type: 'Scripted',
  last_air_date: '2024-11-23',
  homepage: 'https://www.example.com',
});

// Mock Season with Episodes
export const createMockSeasonData = (seasonNumber: number): Season => ({
  id: seasonNumber,
  name: `Season ${seasonNumber}`,
  episode_count: 10,
  season_number: seasonNumber,
  air_date: '2021-11-06',
  overview: `Season ${seasonNumber} of the series.`,
  poster_path: '/qbj7F0OqUb6K6lZKfIvCNcvBT3V.jpg',
  episodes: Array.from({ length: 10 }, (_, i) => ({
    id: seasonNumber * 100 + i + 1,
    name: `Episode ${i + 1}`,
    episode_number: i + 1,
    season_number: seasonNumber,
    overview: `This is episode ${i + 1} of season ${seasonNumber}. An exciting chapter in the story unfolds.`,
    air_date: '2021-11-06',
    runtime: 45,
    vote_average: 7.5 + Math.random(),
    vote_count: Math.floor(Math.random() * 1000) + 100,
    still_path: '/1yNRnZbgfX4JMuR4BxFVKd5K5NV.jpg',
  })),
});
